<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elementTracking</name>
   <tag></tag>
   <elementGuidId>c69b644d-44c8-408c-9cba-2ab12e8ac54a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2121 > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://www.siacargo.com/e-services/quicksearch_public/?transId=' and (text() = 'Tracking' or . = 'Tracking')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Tracking']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f373d6e-3130-4025-97c5-fc4156901ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.siacargo.com/e-services/quicksearch_public/?transId=</value>
      <webElementGuid>5045706a-f04a-4810-8d6a-2886d9776959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tracking</value>
      <webElementGuid>b41e8688-ccbf-4d88-ad62-da411d45d0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2121&quot;)/a[1]</value>
      <webElementGuid>3056a0d3-d8b1-4270-b1e2-1c716fa2b153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2121']/a</value>
      <webElementGuid>4c412393-fbb4-46aa-a5af-44e5ab48849b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tracking')]</value>
      <webElementGuid>1c6343e4-7f3a-4fa0-9652-ae15c445f2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Schedule'])[1]/following::a[1]</value>
      <webElementGuid>a4ea75e4-fb9a-4889-b163-32a6f0cc9393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valuable Cargo'])[1]/following::a[3]</value>
      <webElementGuid>0de9db32-6549-4f18-ab3c-864bddacf332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eTimetable'])[1]/preceding::a[1]</value>
      <webElementGuid>2233d83b-1b93-4679-84d6-4efc51b048c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eAWB'])[1]/preceding::a[2]</value>
      <webElementGuid>27b8c18b-1121-4224-ba58-b50517a4f89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tracking']/parent::*</value>
      <webElementGuid>5a43dcff-f289-4436-8d50-4cb4816ec7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.siacargo.com/e-services/quicksearch_public/?transId=')]</value>
      <webElementGuid>4aac72bc-8f77-46d4-b41d-208c09cf9ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>5e38dc90-1154-4472-a534-b18e2ec18ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.siacargo.com/e-services/quicksearch_public/?transId=' and (text() = 'Tracking' or . = 'Tracking')]</value>
      <webElementGuid>92451e18-fcca-4090-bcd5-ee772229d881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
